"""Generate synthesized context sections for CLAUDE.md and AGENTS.md.

Reads all sessions for a repo from both Codex and Claude Code,
extracts key information, and produces a concise summary section
weighted by recency.
"""

from datetime import datetime, timezone
from typing import List
from lib.codex_reader import CodexReader
from lib.claude_reader import ClaudeReader


def generate_context_section(repo, codex_reader, claude_reader, max_recent=10, recent_days=30):
    """Generate a synthesized context section for a repo.
    Returns a markdown string suitable for CLAUDE.md or AGENTS.md.
    """
    codex_sessions = codex_reader.list_sessions(repo=repo, days_back=recent_days, limit=max_recent)
    claude_sessions = claude_reader.list_sessions(repo=repo, days_back=recent_days, limit=max_recent)
    all_codex = codex_reader.list_sessions(repo=repo, limit=50)
    all_claude = claude_reader.list_sessions(repo=repo, limit=50)

    now = datetime.now(timezone.utc)
    date_str = now.strftime("%Y-%m-%d")

    lines = [
        f"# Cross-Tool Context (auto-generated by context-bridge)",
        f"# Last updated: {date_str}",
        f"# Repo: {repo}",
        "",
    ]

    # Recent work section
    recent = sorted(codex_sessions + claude_sessions, key=lambda s: s.updated_at, reverse=True)[:max_recent]
    if recent:
        lines.append("## Recent Work (last 30 days)")
        for s in recent:
            date = s.updated_at.strftime("%b %d")
            source = s.source.upper()
            title = s.title or s.first_prompt[:80].replace("\n", " ")
            if len(title) > 80:
                title = title[:77] + "..."
            lines.append(f"- {date} [{source}]: {title}")
        lines.append("")

    # All-time summary
    total_codex = len(all_codex)
    total_claude = len(all_claude)
    if total_codex > 0 or total_claude > 0:
        lines.append("## Session History")
        lines.append(f"- Codex sessions: {total_codex}")
        lines.append(f"- Claude Code sessions: {total_claude}")
        all_sessions = all_codex + all_claude
        valid_dates = [s for s in all_sessions if s.created_at.year > 2000]
        if valid_dates:
            earliest = min(s.created_at for s in valid_dates).strftime("%Y-%m-%d")
            latest = max(s.updated_at for s in valid_dates).strftime("%Y-%m-%d")
            lines.append(f"- Date range: {earliest} to {latest}")
        lines.append("")

    # Key topics
    all_sessions = all_codex + all_claude
    if all_sessions:
        lines.append("## Key Topics Discussed")
        seen_topics = set()
        for s in all_sessions[:30]:
            raw_topic = s.title or s.first_prompt
            topic = raw_topic[:80].replace("\n", " ").strip()
            if len(raw_topic) > 80:
                topic += "..."
            topic_key = topic.lower()[:40]
            if topic and topic_key not in seen_topics:
                seen_topics.add(topic_key)
                if len(seen_topics) <= 15:
                    lines.append(f"- {topic}")
        lines.append("")

    return "\n".join(lines)


def sync_repo(repo, codex_reader, claude_reader, target="both"):
    """Generate and return context section for a repo."""
    section = generate_context_section(repo, codex_reader, claude_reader)
    results = []
    if not section.strip():
        return [f"No sessions found for repo '{repo}'."]
    results.append(f"Generated context section for '{repo}':")
    results.append(section)
    results.append("")
    results.append("To use this, paste the above section into your CLAUDE.md or AGENTS.md file.")
    return results
